name: Static Code Analysis

on:
  workflow_call:
    inputs:
      coverage_artifact:
        description: 'The coverage report artifact file name or path to download from the workflow container.'
        required: true
        type: string

jobs:
  static_code_analysis:
        runs-on: ubuntu-latest
        steps:
        # Downloads the coverage report artifact
        - uses: actions/download-artifact@v3
          with:
            name: ${{ inputs.coverage_artifact }}
        # Checkouts the github repository
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0
        # Performs the SonarQube static code analysis scan
        - uses: sonarsource/sonarqube-scan-action@master
          env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_DEV }} # Set as an organization secret
            SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }} # Set as an organization secret